# Generated by Django 6.0 on 2026-01-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_app', '0002_alter_kutubxonaitem_category_alter_quizresult_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amaliyotitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
