# Generated by Django 6.0 on 2026-03-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_app', '0003_alter_amaliyotitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube havolasi'),
        ),
    ]
