# Generated by Django 6.0 on 2026-03-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_app', '0004_news_pdf_news_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='lessons/files'),
        ),
    ]
