# Generated by Django 6.0 on 2026-03-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_app', '0005_lesson_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
