# Generated by Django 6.0 on 2026-03-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_app', '0006_coursetest_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_type', models.CharField(choices=[('url', 'YouTube URL'), ('file', 'Fayl Yuklash')], max_length=10)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
