# Generated by Django 6.0 on 2026-03-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_app', '0008_videocategory_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='kutubxonaitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='library/'),
        ),
    ]
