# Generated by Django 6.0 on 2026-04-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_app', '0009_kutubxonaitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaliyotvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='amaliyot/videos/'),
        ),
        migrations.AddField(
            model_name='amaliyotvideo',
            name='video_type',
            field=models.CharField(choices=[('url', 'YouTube URL'), ('file', 'Fayl Yuklash')], default='default', max_length=50),
            preserve_default=False,
        ),
    ]
