# Generated by Django 6.0 on 2026-04-10 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_app', '0010_amaliyotvideo_video_file_amaliyotvideo_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaliyotvideo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='amaliyotvideo',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AmaliyotItemHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_type', models.CharField(choices=[('pupil', 'O‘quvchiga yordam'), ('teacher', 'O‘qituvchiga yordam')], max_length=20)),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helps', to='inclusive_app.amaliyotitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
